services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .envs/prod/api.env
