services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${SERVER_ENVIRONMENT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .envs/local/api.env
      - .envs/local/db.env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${SERVER_ENVIRONMENT}
    command: celery -A src.core.celery worker --loglevel=info
    env_file:
      - .envs/local/api.env
      - .envs/local/db.env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:18
    env_file:
      - .envs/local/db.env
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8.8.0
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
