"""add ticket and ticket history tables

Revision ID: 4108584de64d
Revises: 576739a739c1
Create Date: 2026-06-21 13:11:37.475594+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4108584de64d'
down_revision: Union[str, Sequence[str], None] = '576739a739c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.Column('agent', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=11), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modified_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_history',
    sa.Column('ticket', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=13), nullable=False),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_history')
    op.drop_table('tickets')
    # ### end Alembic commands ###
